<?php
/**
 * DNSSecondaryNameserverResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MailInABoxAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * DNSSecondaryNameserverResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Secondary nameserver/s response.
 * @package     MailInABoxAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DNSSecondaryNameserverResponseTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DNSSecondaryNameserverResponse"
     */
    public function testDNSSecondaryNameserverResponse()
    {
    }

    /**
     * Test attribute "hostnames"
     */
    public function testPropertyHostnames()
    {
    }
}
