<?php
/**
 * SystemBackupConfigUpdateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MailInABoxAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * SystemBackupConfigUpdateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Backup config update request.
 * @package     MailInABoxAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SystemBackupConfigUpdateRequestTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SystemBackupConfigUpdateRequest"
     */
    public function testSystemBackupConfigUpdateRequest()
    {
    }

    /**
     * Test attribute "target"
     */
    public function testPropertyTarget()
    {
    }

    /**
     * Test attribute "targetUser"
     */
    public function testPropertyTargetUser()
    {
    }

    /**
     * Test attribute "targetPass"
     */
    public function testPropertyTargetPass()
    {
    }

    /**
     * Test attribute "minAge"
     */
    public function testPropertyMinAge()
    {
    }
}
