<?php
/**
 * DNSApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailInABoxAPI\Client;

use MailInABoxAPI\Client\Configuration;
use MailInABoxAPI\Client\ApiException;
use MailInABoxAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DNSApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DNSApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addDnsCustomARecord
     *
     * Add DNS custom A record.
     *
     */
    public function testAddDnsCustomARecord()
    {
    }

    /**
     * Test case for addDnsCustomRecord
     *
     * Add DNS custom record.
     *
     */
    public function testAddDnsCustomRecord()
    {
    }

    /**
     * Test case for addDnsSecondaryNameserver
     *
     * Add DNS secondary nameserver.
     *
     */
    public function testAddDnsSecondaryNameserver()
    {
    }

    /**
     * Test case for getDnsCustomARecordsForQName
     *
     * Get DNS custom A records.
     *
     */
    public function testGetDnsCustomARecordsForQName()
    {
    }

    /**
     * Test case for getDnsCustomRecords
     *
     * Get DNS custom records.
     *
     */
    public function testGetDnsCustomRecords()
    {
    }

    /**
     * Test case for getDnsCustomRecordsForQNameAndType
     *
     * Get DNS custom records.
     *
     */
    public function testGetDnsCustomRecordsForQNameAndType()
    {
    }

    /**
     * Test case for getDnsDump
     *
     * Get DNS dump.
     *
     */
    public function testGetDnsDump()
    {
    }

    /**
     * Test case for getDnsSecondaryNameserver
     *
     * Get DNS secondary nameserver.
     *
     */
    public function testGetDnsSecondaryNameserver()
    {
    }

    /**
     * Test case for getDnsZones
     *
     * Get DNS zones.
     *
     */
    public function testGetDnsZones()
    {
    }

    /**
     * Test case for removeDnsCustomARecord
     *
     * Remove DNS custom A record.
     *
     */
    public function testRemoveDnsCustomARecord()
    {
    }

    /**
     * Test case for removeDnsCustomRecord
     *
     * Remove DNS custom record.
     *
     */
    public function testRemoveDnsCustomRecord()
    {
    }

    /**
     * Test case for updateDns
     *
     * Update DNS.
     *
     */
    public function testUpdateDns()
    {
    }

    /**
     * Test case for updateDnsCustomARecord
     *
     * Update DNS custom A record.
     *
     */
    public function testUpdateDnsCustomARecord()
    {
    }

    /**
     * Test case for updateDnsCustomRecord
     *
     * Update DNS custom record.
     *
     */
    public function testUpdateDnsCustomRecord()
    {
    }
}
