<?php
/**
 * DNSApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailInABoxAPI\Client;

use MailInABoxAPI\Client\Configuration;
use MailInABoxAPI\Client\ApiException;
use MailInABoxAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DNSApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DNSApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addDnsCustomRecord
     *
     * .
     *
     */
    public function testAddDnsCustomRecord()
    {
    }

    /**
     * Test case for addDnsCustomRecordForTypeA
     *
     * .
     *
     */
    public function testAddDnsCustomRecordForTypeA()
    {
    }

    /**
     * Test case for addDnsSecondaryNameserver
     *
     * .
     *
     */
    public function testAddDnsSecondaryNameserver()
    {
    }

    /**
     * Test case for getDnsCustomRecords
     *
     * .
     *
     */
    public function testGetDnsCustomRecords()
    {
    }

    /**
     * Test case for getDnsCustomRecordsForDomainAndType
     *
     * .
     *
     */
    public function testGetDnsCustomRecordsForDomainAndType()
    {
    }

    /**
     * Test case for getDnsCustomRecordsForDomainAndTypeA
     *
     * .
     *
     */
    public function testGetDnsCustomRecordsForDomainAndTypeA()
    {
    }

    /**
     * Test case for getDnsDump
     *
     * .
     *
     */
    public function testGetDnsDump()
    {
    }

    /**
     * Test case for getDnsSecondaryNameserver
     *
     * .
     *
     */
    public function testGetDnsSecondaryNameserver()
    {
    }

    /**
     * Test case for getDnsZones
     *
     * .
     *
     */
    public function testGetDnsZones()
    {
    }

    /**
     * Test case for removeDnsCustomRecord
     *
     * .
     *
     */
    public function testRemoveDnsCustomRecord()
    {
    }

    /**
     * Test case for removeDnsCustomRecordForTypeA
     *
     * .
     *
     */
    public function testRemoveDnsCustomRecordForTypeA()
    {
    }

    /**
     * Test case for updateDns
     *
     * .
     *
     */
    public function testUpdateDns()
    {
    }

    /**
     * Test case for updateDnsCustomRecord
     *
     * .
     *
     */
    public function testUpdateDnsCustomRecord()
    {
    }

    /**
     * Test case for updateDnsCustomRecordForTypeA
     *
     * .
     *
     */
    public function testUpdateDnsCustomRecordForTypeA()
    {
    }
}
