<?php
/**
 * MailApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailInABoxAPI\Client;

use MailInABoxAPI\Client\Configuration;
use MailInABoxAPI\Client\ApiException;
use MailInABoxAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MailApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MailApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMailUser
     *
     * .
     *
     */
    public function testAddMailUser()
    {
    }

    /**
     * Test case for addMailUserPrivilege
     *
     * .
     *
     */
    public function testAddMailUserPrivilege()
    {
    }

    /**
     * Test case for getMailAliases
     *
     * .
     *
     */
    public function testGetMailAliases()
    {
    }

    /**
     * Test case for getMailDomains
     *
     * .
     *
     */
    public function testGetMailDomains()
    {
    }

    /**
     * Test case for getMailUserPrivileges
     *
     * .
     *
     */
    public function testGetMailUserPrivileges()
    {
    }

    /**
     * Test case for getMailUsers
     *
     * .
     *
     */
    public function testGetMailUsers()
    {
    }

    /**
     * Test case for removeMailAlias
     *
     * .
     *
     */
    public function testRemoveMailAlias()
    {
    }

    /**
     * Test case for removeMailUser
     *
     * .
     *
     */
    public function testRemoveMailUser()
    {
    }

    /**
     * Test case for removeMailUserPrivilege
     *
     * .
     *
     */
    public function testRemoveMailUserPrivilege()
    {
    }

    /**
     * Test case for setMailUserPassword
     *
     * .
     *
     */
    public function testSetMailUserPassword()
    {
    }

    /**
     * Test case for upsertMailAlias
     *
     * .
     *
     */
    public function testUpsertMailAlias()
    {
    }
}
