<?php
/**
 * MailApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailInABoxAPI\Client;

use MailInABoxAPI\Client\Configuration;
use MailInABoxAPI\Client\ApiException;
use MailInABoxAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MailApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MailApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMailUser
     *
     * Add mail user.
     *
     */
    public function testAddMailUser()
    {
    }

    /**
     * Test case for addMailUserPrivilege
     *
     * Add mail user privilege.
     *
     */
    public function testAddMailUserPrivilege()
    {
    }

    /**
     * Test case for getMailAliases
     *
     * Get mail aliases.
     *
     */
    public function testGetMailAliases()
    {
    }

    /**
     * Test case for getMailDomains
     *
     * Get mail domains.
     *
     */
    public function testGetMailDomains()
    {
    }

    /**
     * Test case for getMailUserPrivileges
     *
     * Get mail user privileges.
     *
     */
    public function testGetMailUserPrivileges()
    {
    }

    /**
     * Test case for getMailUsers
     *
     * Get mail users.
     *
     */
    public function testGetMailUsers()
    {
    }

    /**
     * Test case for removeMailAlias
     *
     * Remove mail alias.
     *
     */
    public function testRemoveMailAlias()
    {
    }

    /**
     * Test case for removeMailUser
     *
     * Remove mail user.
     *
     */
    public function testRemoveMailUser()
    {
    }

    /**
     * Test case for removeMailUserPrivilege
     *
     * Remove mail user privilege.
     *
     */
    public function testRemoveMailUserPrivilege()
    {
    }

    /**
     * Test case for setMailUserPassword
     *
     * Set mail user password.
     *
     */
    public function testSetMailUserPassword()
    {
    }

    /**
     * Test case for upsertMailAlias
     *
     * Upsert mail alias.
     *
     */
    public function testUpsertMailAlias()
    {
    }
}
