<?php
/**
 * SystemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailInABoxAPI\Client;

use MailInABoxAPI\Client\Configuration;
use MailInABoxAPI\Client\ApiException;
use MailInABoxAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SystemApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SystemApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getSystemBackupConfig
     *
     * .
     *
     */
    public function testGetSystemBackupConfig()
    {
    }

    /**
     * Test case for getSystemBackupStatus
     *
     * .
     *
     */
    public function testGetSystemBackupStatus()
    {
    }

    /**
     * Test case for getSystemPrivacyStatus
     *
     * .
     *
     */
    public function testGetSystemPrivacyStatus()
    {
    }

    /**
     * Test case for getSystemRebootStatus
     *
     * .
     *
     */
    public function testGetSystemRebootStatus()
    {
    }

    /**
     * Test case for getSystemStatus
     *
     * .
     *
     */
    public function testGetSystemStatus()
    {
    }

    /**
     * Test case for getSystemUpdates
     *
     * .
     *
     */
    public function testGetSystemUpdates()
    {
    }

    /**
     * Test case for getSystemUpstreamVersion
     *
     * .
     *
     */
    public function testGetSystemUpstreamVersion()
    {
    }

    /**
     * Test case for getSystemVersion
     *
     * .
     *
     */
    public function testGetSystemVersion()
    {
    }

    /**
     * Test case for rebootSystem
     *
     * .
     *
     */
    public function testRebootSystem()
    {
    }

    /**
     * Test case for updateSystemBackupConfig
     *
     * .
     *
     */
    public function testUpdateSystemBackupConfig()
    {
    }

    /**
     * Test case for updateSystemPackages
     *
     * .
     *
     */
    public function testUpdateSystemPackages()
    {
    }

    /**
     * Test case for updateSystemPrivacy
     *
     * .
     *
     */
    public function testUpdateSystemPrivacy()
    {
    }
}
