<?php
/**
 * SystemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mail-in-a-Box
 *
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailInABoxAPI\Client;

use MailInABoxAPI\Client\Configuration;
use MailInABoxAPI\Client\ApiException;
use MailInABoxAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SystemApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailInABoxAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SystemApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getSystemBackupConfig
     *
     * Get system backup config.
     *
     */
    public function testGetSystemBackupConfig()
    {
    }

    /**
     * Test case for getSystemBackupStatus
     *
     * Get system backup status.
     *
     */
    public function testGetSystemBackupStatus()
    {
    }

    /**
     * Test case for getSystemPrivacyStatus
     *
     * Get system privacy status.
     *
     */
    public function testGetSystemPrivacyStatus()
    {
    }

    /**
     * Test case for getSystemRebootStatus
     *
     * Get system reboot status.
     *
     */
    public function testGetSystemRebootStatus()
    {
    }

    /**
     * Test case for getSystemStatus
     *
     * Get system status.
     *
     */
    public function testGetSystemStatus()
    {
    }

    /**
     * Test case for getSystemUpdates
     *
     * Get system updates.
     *
     */
    public function testGetSystemUpdates()
    {
    }

    /**
     * Test case for getSystemUpstreamVersion
     *
     * Get system upstream version.
     *
     */
    public function testGetSystemUpstreamVersion()
    {
    }

    /**
     * Test case for getSystemVersion
     *
     * Get system version.
     *
     */
    public function testGetSystemVersion()
    {
    }

    /**
     * Test case for rebootSystem
     *
     * Reboot system.
     *
     */
    public function testRebootSystem()
    {
    }

    /**
     * Test case for updateSystemBackupConfig
     *
     * Update system backup config.
     *
     */
    public function testUpdateSystemBackupConfig()
    {
    }

    /**
     * Test case for updateSystemPackages
     *
     * Update system packages.
     *
     */
    public function testUpdateSystemPackages()
    {
    }

    /**
     * Test case for updateSystemPrivacy
     *
     * Update system privacy.
     *
     */
    public function testUpdateSystemPrivacy()
    {
    }
}
